In [12]:
import sys
sys.path.append("../") # go to parent dir

from custom_helpers_py.utilities import camel_to_snake_case
import pandas as pd
from os import listdir
from os.path import join
import json

In [13]:
COMPRESSED_FOLDER_PATH = join("../.outFiles/analysis/compressed")
SENATE_FILE_PATH = join("../.outFiles/watcher/senate_watcher.csv")
HOUSE_FILE_PATH = join("../.outFiles/watcher/house_watcher.csv")

def get_doc_id(in_str:str):
    in_str = in_str.removesuffix("/")
    last_slash_idx = in_str.rfind("/")
    doc_id = in_str[last_slash_idx + 1:]
    doc_id = doc_id.removesuffix(".pdf")
    return doc_id
    
senate_df = pd.read_csv(SENATE_FILE_PATH, encoding="utf-8")
senate_df["doc_id"] = senate_df["ptr_link"].apply(get_doc_id)
senate_df = senate_df.drop(columns=["ptr_link"])
senate_df.columns = [
    "tx_date",
    "owner",
    "ticker",
    "asset_name",
    "asset_type",
    "tx_type",
    "amount",
    "comments",
    "p_party",
    "p_state",
    "asset_industry",
    "asset_sector",
    "p_full_name",
    "notif_date",
    "doc_id"
]
senate_df["data_source"] = "WATCHER_SENATE"

to_save_path = join(COMPRESSED_FOLDER_PATH, "watcher_senate.csv")
senate_df.to_csv(to_save_path, index=False, header=True)

senate_df

,tx_date,owner,ticker,asset_name,asset_type,tx_type,amount,comments,p_party,p_state,asset_industry,asset_sector,p_full_name,notif_date,doc_id,data_source
0,04/18/2023,Spouse,ESS,"Essex Property Trust, Inc. Common Stock",Stock,Sale (Full),"$1,001 - $15,000",--,Democrat,RI,Real Estate Investment Trusts,Consumer Services,Sheldon Whitehouse,05/17/2023,9fc025a0-f893-47b2-9252-a2820737a409,WATCHER_SENATE
1,04/18/2023,Self,ESS,"Essex Property Trust, Inc. Common Stock",Stock,Sale (Full),"$1,001 - $15,000",--,Democrat,RI,Real Estate Investment Trusts,Consumer Services,Sheldon Whitehouse,05/17/2023,9fc025a0-f893-47b2-9252-a2820737a409,WATCHER_SENATE
2,05/16/2023,NaN,NaN,This filing was disclosed via scanned PDF. Use...,PDF Disclosed Filing,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Michael F. Bennet,05/16/2023,f590a331-1f74-4d08-b79f-88930593f314,WATCHER_SENATE
3,04/04/2023,Spouse,UPS,"United Parcel Service, Inc. Common Stock",Stock,Sale (Full),"$1,001 - $15,000",--,Republican,WV,Trucking Freight/Courier Services,Transportation,Shelley Moore Capito,05/15/2023,60987939-a116-41ee-86c2-8ba920461691,WATCHER_SENATE
4,04/04/2023,Spouse,MCD,McDonald's Corporation Common Stock,Stock,Sale (Partial),"$1,001 - $15,000",--,Republican,WV,Restaurants,Consumer Services,Shelley Moore Capito,05/15/2023,60987939-a116-41ee-86c2-8ba920461691,WATCHER_SENATE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8441,08/17/2012,NaN,NaN,This filing was disclosed via scanned PDF. Use...,PDF Disclosed Filing,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Sheldon Whitehouse,08/17/2012,5221D7D8-15D0-40FE-A64C-DD242311F0AE,WATCHER_SENATE
8442,08/16/2012,NaN,NaN,This filing was disclosed via scanned PDF. Use...,PDF Disclosed Filing,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Pat Roberts,08/16/2012,5C666F29-7055-461D-B4F7-5EA73AFCD860,WATCHER_SENATE
8443,08/15/2012,NaN,NaN,This filing was disclosed via scanned PDF. Use...,PDF Disclosed Filing,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Rob Portman,08/15/2012,0D78FC31-D28A-440A-8E2D-65C4D9861EAB,WATCHER_SENATE
8444,08/02/2012,NaN,NaN,This filing was disclosed via scanned PDF. Use...,PDF Disclosed Filing,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Thomas R. Carper,08/02/2012,CFDE3B80-E8BD-4F2D-9D64-E892C5EFB32A,WATCHER_SENATE
8445,07/25/2012,NaN,NaN,This filing was disclosed via scanned PDF. Use...,PDF Disclosed Filing,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Benjamin L Cardin,07/25/2012,CDFDAF62-18EA-4298-B0C5-62085A6EC3CD,WATCHER_SENATE

In [14]:
house_df = pd.read_csv(HOUSE_FILE_PATH, encoding="utf-8")

house_df["doc_id"] = house_df["ptr_link"].apply(get_doc_id)
house_df = house_df.drop(columns=["disclosure_year", "ptr_link"])
house_df.columns = [
    "notif_date",
    "tx_date",
    "owner",
    "ticker",
    "asset_name",
    "tx_type",
    "amount",
    "p_full_name",
    "p_district",
    "p_state",
    "cap_gains_over_200_usd",
    "asset_industry",
    "asset_sector",
    "p_party",
    "doc_id"
]
house_df["data_source"] = "WATCHER_HOUSE"

to_save_path = join(COMPRESSED_FOLDER_PATH, "watcher_house.csv")
house_df.to_csv(to_save_path, index=False, header=True)

house_df

,notif_date,tx_date,owner,ticker,asset_name,tx_type,amount,p_full_name,p_district,p_state,cap_gains_over_200_usd,asset_industry,asset_sector,p_party,doc_id,data_source
0,10/04/2021,2021-09-27,joint,BP,BP plc,purchase,"$1,001 - $15,000",Virginia Foxx,NC05,NC,False,Integrated oil Companies,Energy,Republican,20019557,WATCHER_HOUSE
1,10/04/2021,2021-09-13,joint,XOM,Exxon Mobil Corporation,purchase,"$1,001 - $15,000",Virginia Foxx,NC05,NC,False,Integrated oil Companies,Energy,Republican,20019557,WATCHER_HOUSE
2,10/04/2021,2021-09-10,joint,ILPT,Industrial Logistics Properties Trust - Common...,purchase,"$15,001 - $50,000",Virginia Foxx,NC05,NC,False,Real Estate Investment Trusts,Real Estate,Republican,20019557,WATCHER_HOUSE
3,10/04/2021,2021-09-28,joint,PM,Phillip Morris International Inc,purchase,"$15,001 - $50,000",Virginia Foxx,NC05,NC,False,Farming/Seeds/Milling,Consumer Non-Durables,Republican,20019557,WATCHER_HOUSE
4,10/04/2021,2021-09-17,self,BLK,BlackRock Inc,sale_partial,"$1,001 - $15,000",Alan S. Lowenthal,CA47,CA,False,Investment Bankers/Brokers/Service,Finance,Democrat,20019570,WATCHER_HOUSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17165,06/10/2020,2020-04-09,--,SWK,"Stanley Black & Decker, Inc.",sale_partial,"$1,001 - $15,000",Ed Perlmutter,CO07,CO,False,Diversified Manufacture,Consumer Discretionary,Democrat,20016738,WATCHER_HOUSE
17166,06/10/2020,2020-04-09,--,USB,U.S. Bancorp,sale_partial,"$1,001 - $15,000",Ed Perlmutter,CO07,CO,False,Major Banks,Finance,Democrat,20016738,WATCHER_HOUSE
17167,06/10/2020,2020-03-13,NaN,BMY,Bristol-Myers Squibb Company,sale_full,"$100,001 - $250,000",Van Taylor,TX03,TX,False,Major Pharmaceuticals,Health Care,Republican,20016703,WATCHER_HOUSE
17168,06/10/2020,2020-03-13,NaN,LLY,Eli Lilly and Company,sale_full,"$500,001 - $1,000,000",Van Taylor,TX03,TX,False,Major Pharmaceuticals,Health Care,Republican,20016703,WATCHER_HOUSE
17169,06/10/2020,2020-03-13,NaN,DIS,Walt Disney Company,sale_full,"$250,001 - $500,000",Van Taylor,TX03,TX,False,Services-Misc. Amusement & Recreation,Consumer Services,Republican,20016703,WATCHER_HOUSE