In [2]:
import sys

sys.path.append("../") # go to parent dir

import pandas as pd
import numpy as np
from custom_helpers_py.get_paths import get_out_folder_house, get_out_folder_senate, get_out_folder_analysis
from os.path import join
from os import listdir
import math

In [3]:
COMPRESSED_SENATE_FILE_PATH = join(get_out_folder_senate(), "compressed", "master_senate.csv")
COMPRESSED_HOUSE_FILE_PATH = join(get_out_folder_house(), "compressed", "master_house.csv")

master_df = pd.concat([
    pd.read_csv(COMPRESSED_SENATE_FILE_PATH),
    pd.read_csv(COMPRESSED_HOUSE_FILE_PATH),
    ], axis=0)

raw_size = master_df.size

# Remove those with null dates, amounts, or action_types
master_df = master_df.dropna(subset=[
    "transaction_date",
    "action_type",
    "amount"
])

no_na_size = master_df.size
removed = raw_size - no_na_size

print("removed", removed)

# Fix tickers
def fix_tickers(in_ticker: None | str):
    if not isinstance(in_ticker, str):
        return np.nan 
    if in_ticker == "--":
        return np.nan
    if "--" in in_ticker or "\n" in in_ticker:
        in_ticker = in_ticker.replace("--", "").replace("\n", "")
    
    if "FB" == in_ticker:
        return "META"
    
    FORBIDDEN_SUB_STRING_LIST = [
        "/",
        " ",
        "%",
        "["
    ]
    for sub_str in FORBIDDEN_SUB_STRING_LIST:
        if sub_str in in_ticker:
            return pd.NA

    return in_ticker

master_df["ticker"] = master_df["ticker"].apply(fix_tickers)

# Process dates
def fix_dates(in_date_str:str):
    month, day, year = in_date_str.split("/")
    if year.startswith("3"):
        year = "2" + year[1:]
    
    if year == "2031":
        year = "2021"
        
    if year == "2202":
        year = "2020"
        
    if year == "2220":
        year = "2020"
    
    
    to_return = "/".join([month, day, year])
    return to_return

master_df["transaction_date"] = master_df["transaction_date"].apply(fix_dates)
master_df["transaction_date"] = pd.to_datetime( master_df["transaction_date"], format="%m/%d/%Y")

# Process amounts
def get_lower_bound_amount(in_amount:str):
    to_return = in_amount
    if "-" in in_amount:
        to_return = in_amount.split("-")[0]
    elif "Over" in in_amount:
        to_return = in_amount.replace("Over", "")

    to_return = to_return.replace("$", "").replace(",", "").strip()
    return float(to_return)

def get_upper_bound_amount(in_amount:str):
    to_return = in_amount
    if "-" in in_amount:
        to_return = in_amount.split("-")[1]
    elif "Over" in in_amount:
        to_return = in_amount.replace("Over", "")

    to_return = to_return.replace("$", "").replace(",", "").strip()
    return float(to_return)

def get_average_amount(in_amount):
    lower_bound, upper_bound = get_lower_bound_amount(in_amount), get_upper_bound_amount(in_amount)

    if upper_bound == np.nan:
        return np.nan
    
    return (upper_bound + lower_bound) / 2
    
master_df["lower_bound_amount"] = master_df["amount"].apply(get_lower_bound_amount)
master_df["upper_bound_amount"] = master_df["amount"].apply(get_upper_bound_amount)
master_df["average_amount"] = master_df["amount"].apply(get_average_amount)

# combine names
master_df["politician_name"] = master_df["politician_first_name"]+ " " + master_df["politician_last_name"]
    
master_df.sort_values(inplace=True, by="transaction_date")

master_df_file_path = join(get_out_folder_analysis(), "master_df.csv")
master_df.to_csv(master_df_file_path, encoding="utf-8", index=False)
master_df

removed 14

,transaction_date,politician_first_name,politician_last_name,office,district,asset_name,asset_type,ticker,owner,action_type,action_type_extra,amount,comments,doc_id,lower_bound_amount,upper_bound_amount,average_amount,politician_name
4267,2011-11-29,ROBERT-P,CORKER-JR,S,NaN,CBL & Associates Properties Inc. - CBL,ST,NaN,SELF,P,NaN,"$1,000,001 - $5,000,000",--,ccf1abc0-3446-4745-a17f-9a6ee9ea32ec,1000001.0,5000000.0,3000000.5,ROBERT-P CORKER-JR
239,2012-02-16,THAD,COCHRAN,S,NaN,"C&J Energy Services, Inc. (NYSE)",NaN,CJES,SELF,S,NaN,"$15,001 - $50,000",--,789c0754-cce2-4dd7-8171-4ac29912e00c,15001.0,50000.0,32500.5,THAD COCHRAN
172,2012-02-16,THAD,COCHRAN,S,NaN,"C&J Energy Services, Inc. (NYSE)",NaN,CJES,SELF,S,NaN,"$15,001 - $50,000",--,4ef44b12-1181-41cc-932a-431ec798f52e,15001.0,50000.0,32500.5,THAD COCHRAN
120,2012-02-27,MR-ALAN-S,LOWENTHAL,H,CA47,E] PASO CORPORATION PREFERRED STOCK,NaN,EP$C,SP,S,NaN,"$1,001 - $15,000",FILING STATUS: NEW,20000945,1001.0,15000.0,8000.5,MR-ALAN-S LOWENTHAL
121,2012-03-20,MR-ALAN-S,LOWENTHAL,H,CA47,E] PASO CORPORATION PREFERRED STOCK,NaN,EP$C,SP,S,NaN,"$1,001 - $15,000",FILING STATUS: NEW,20000945,1001.0,15000.0,8000.5,MR-ALAN-S LOWENTHAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43598,2024-02-21,NANCY,PELOSI,H,CA11,"PALO ALTO NETWORKS, INC.",OP,PANW,SP,P,NaN,"$100,001 - $250,000",NaN,20024542,100001.0,250000.0,175000.5,NANCY PELOSI
43844,2024-02-21,KATHY,MANNING,H,NC06,SB DPC FUND LP,HN,NaN,SP,P,NaN,"$100,001 - $250,000",NaN,20024604,100001.0,250000.0,175000.5,KATHY MANNING
17996,2024-02-22,THOMAS-R,CARPER,S,NaN,US TREASURY BILL,Other Securities,NaN,SP,P,NaN,"$15,001 - $50,000",--,d6290ba2-3a9e-4774-bcd6-6bd2d90e4138,15001.0,50000.0,32500.5,THOMAS-R CARPER
43973,2024-02-26,MARK-DR,GREEN,H,TN07,NGL ENERGY PARTNERS LP COMMON UNITS REPRESENTI...,ST,NGL,SELF,S,NaN,"$50,001 - $100,000",NaN,20024572,50001.0,100000.0,75000.5,MARK-DR GREEN
43982,2024-02-29,PETE,SESSIONS,H,TX17,APPLE INC. COMMON STOCK,ST,AAPL,SP,P,NaN,$360.00,FILING STATUS: NEW SUBHOLDING OF: IRA ONE,20024375,360.0,360.0,360.0,PETE SESSIONS

In [4]:
# Get tickers only
unique_ticker_df = master_df["ticker"].dropna().value_counts().reset_index()
unique_ticker_df.columns = ["ticker", "count"] 
unique_ticker_list = unique_ticker_df.to_dict(orient="records")

unique_ticker_df_file_path = join(get_out_folder_analysis(), "unique_ticker_df.json")
unique_ticker_df.to_json(unique_ticker_df_file_path, orient="records", indent=4)
unique_ticker_list

[{'ticker': 'MSFT', 'count': 829},
 {'ticker': 'AAPL', 'count': 806},
 {'ticker': 'AMZN', 'count': 346},
 {'ticker': 'PARTIAL', 'count': 341},
 {'ticker': 'META', 'count': 310},
 {'ticker': 'DIS', 'count': 309},
 {'ticker': 'JNJ', 'count': 281},
 {'ticker': 'T', 'count': 281},
 {'ticker': 'PFE', 'count': 269},
 {'ticker': 'JPM', 'count': 255},
 {'ticker': 'NVDA', 'count': 247},
 {'ticker': 'INTC', 'count': 244},
 {'ticker': 'VZ', 'count': 236},
 {'ticker': 'PG', 'count': 226},
 {'ticker': 'HD', 'count': 221},
 {'ticker': 'UNH', 'count': 219},
 {'ticker': 'GOOG', 'count': 218},
 {'ticker': 'GE', 'count': 217},
 {'ticker': 'V', 'count': 214},
 {'ticker': 'BAC', 'count': 212},
 {'ticker': 'CVX', 'count': 201},
 {'ticker': 'TSLA', 'count': 200},
 {'ticker': 'WFC', 'count': 198},
 {'ticker': 'SBUX', 'count': 195},
 {'ticker': 'MRK', 'count': 192},
 {'ticker': 'PYPL', 'count': 191},
 {'ticker': 'CVS', 'count': 188},
 {'ticker': 'PEP', 'count': 188},
 {'ticker': 'BA', 'count': 183},
 {'ticker': 'NFLX', 'count': 183},
 {'ticker': 'QCOM', 'count': 181},
 {'ticker': 'COST', 'count': 180},
 {'ticker': 'GOOGL', 'count': 176},
 {'ticker': 'CSCO', 'count': 175},
 {'ticker': 'ACN', 'count': 174},
 {'ticker': 'SLB', 'count': 173},
 {'ticker': 'IBM', 'count': 170},
 {'ticker': 'MDT', 'count': 167},
 {'ticker': 'BRK.B', 'count': 167},
 {'ticker': 'NEE', 'count': 165},
 {'ticker': 'KO', 'count': 164},
 {'ticker': 'BABA', 'count': 159},
 {'ticker': 'TJX', 'count': 159},
 {'ticker': 'TXN', 'count': 154},
 {'ticker': 'ABBV', 'count': 151},
 {'ticker': 'MA', 'count': 147},
 {'ticker': 'CMCSA', 'count': 147},
 {'ticker': 'C', 'count': 146},
 {'ticker': 'WMT', 'count': 143},
 {'ticker': 'FDX', 'count': 139},
 {'ticker': 'AMGN', 'count': 138},
 {'ticker': 'KOM', 'count': 136},
 {'ticker': 'GILD', 'count': 134},
 {'ticker': 'D', 'count': 134},
 {'ticker': 'LMT', 'count': 133},
 {'ticker': 'DD', 'count': 133},
 {'ticker': 'BMY', 'count': 130},
 {'ticker': 'MCD', 'count': 129},
 {'ticker': 'XOM', 'count': 127},
 {'ticker': 'UPS', 'count': 126},
 {'ticker': 'ORCL', 'count': 126},
 {'ticker': 'MMM', 'count': 124},
 {'ticker': 'DISCA', 'count': 122},
 {'ticker': 'UNP', 'count': 122},
 {'ticker': 'MO', 'count': 119},
 {'ticker': 'HON', 'count': 119},
 {'ticker': 'PM', 'count': 115},
 {'ticker': 'GM', 'count': 115},
 {'ticker': 'BLK', 'count': 115},
 {'ticker': 'ET', 'count': 114},
 {'ticker': 'AXP', 'count': 112},
 {'ticker': 'TMO', 'count': 111},
 {'ticker': 'RUN', 'count': 110},
 {'ticker': 'WMB', 'count': 109},
 {'ticker': 'EMR', 'count': 108},
 {'ticker': 'NVS', 'count': 108},
 {'ticker': 'F', 'count': 108},
 {'ticker': 'GS', 'count': 107},
 {'ticker': 'LLY', 'count': 107},
 {'ticker': 'ABT', 'count': 105},
 {'ticker': 'CAT', 'count': 104},
 {'ticker': 'DHR', 'count': 101},
 {'ticker': 'UTX', 'count': 100},
 {'ticker': 'NSRGY', 'count': 98},
 {'ticker': 'USB', 'count': 98},
 {'ticker': 'COP', 'count': 97},
 {'ticker': 'CB', 'count': 97},
 {'ticker': 'GIS', 'count': 97},
 {'ticker': 'CL', 'count': 96},
 {'ticker': 'NKE', 'count': 96},
 {'ticker': 'SPY', 'count': 96},
 {'ticker': 'EPD', 'count': 94},
 {'ticker': 'LOW', 'count': 94},
 {'ticker': 'KR', 'count': 94},
 {'ticker': 'FIS', 'count': 92},
 {'ticker': 'CLF', 'count': 91},
 {'ticker': 'AM', 'count': 91},
 {'ticker': 'NGL', 'count': 90},
 {'ticker': 'ADBE', 'count': 88},
 {'ticker': 'MCK', 'count': 88},
 {'ticker': 'BIIB', 'count': 88},
 {'ticker': 'BAX', 'count': 88},
 {'ticker': 'CRM', 'count': 87},
 {'ticker': 'OXY', 'count': 87},
 {'ticker': 'TGT', 'count': 87},
 {'ticker': 'RHHBY', 'count': 86},
 {'ticker': 'GSK', 'count': 86},
 {'ticker': 'OKE', 'count': 85},
 {'ticker': 'SQ', 'count': 85},
 {'ticker': 'DE', 'count': 85},
 {'ticker': 'VFC', 'count': 85},
 {'ticker': 'CZR', 'count': 83},
 {'ticker': 'DOW', 'count': 83},
 {'ticker': 'ESRX', 'count': 82},
 {'ticker': 'MOS', 'count': 81},
 {'ticker': 'CI', 'count': 81},
 {'ticker': 'TWTR', 'count': 81},
 {'ticker': 'SO', 'count': 80},
 {'ticker': 'CBS', 'count': 80},
 {'ticker': 'COF', 'count': 80},
 {'ticker': 'PAA', 'count': 79},
 {'ticker': 'KMB', 'count': 79},
 {'ticker': 'FDC', 'count': 78},
 {'ticker': 'JCI', 'count': 78},
 {'ticker': 'FEYE', 'count': 78},
 {'ticker': 'EL', 'count': 78},
 {'ticker': 'ECL', 'count': 78},
 {'ticker': 'SYY', 'count': 77},
 {'ticker': 'WPX', 'count': 76},
 {'ticker': 'INTU', 'count': 75},
 {'ticker': 'IP', 'count': 75},
 {'ticker': 'MET', 'count': 75},
 {'ticker': 'WBA', 'count': 74},
 {'ticker': 'DVN', 'count': 74},
 {'ticker': 'CLX', 'count': 74},
 {'ticker': 'ADP', 'count': 74},
 {'ticker': 'GNRC', 'count': 73},
 {'ticker': 'BSX', 'count': 73},
 {'ticker': 'DFS', 'count': 73},
 {'ticker': 'AGN', 'count': 73},
 {'ticker': 'M', 'count': 73},
 {'ticker': 'DUK', 'count': 73},
 {'ticker': 'CELG', 'count': 72},
 {'ticker': 'GPK', 'count': 72},
 {'ticker': 'PPG', 'count': 72},
 {'ticker': 'ATVI', 'count': 72},
 {'ticker': 'STT', 'count': 71},
 {'ticker': 'GLW', 'count': 71},
 {'ticker': 'SCHW', 'count': 70},
 {'ticker': 'ETN', 'count': 70},
 {'ticker': 'SYK', 'count': 70},
 {'ticker': 'BX', 'count': 70},
 {'ticker': 'CTSH', 'count': 69},
 {'ticker': 'DG', 'count': 68},
 {'ticker': 'KN', 'count': 68},
 {'ticker': 'AAL', 'count': 67},
 {'ticker': 'ZTS', 'count': 67},
 {'ticker': 'URBN', 'count': 66},
 {'ticker': 'KMI', 'count': 66},
 {'ticker': 'TSM', 'count': 65},
 {'ticker': 'BRK-B', 'count': 65},
 {'ticker': 'NOC', 'count': 65},
 {'ticker': 'LYV', 'count': 65},
 {'ticker': 'DEO', 'count': 65},
 {'ticker': 'AMD', 'count': 64},
 {'ticker': 'UL', 'count': 64},
 {'ticker': 'SPG', 'count': 64},
 {'ticker': 'AVGO', 'count': 63},
 {'ticker': 'CME', 'count': 63},
 {'ticker': 'PSX', 'count': 63},
 {'ticker': 'WDC', 'count': 63},
 {'ticker': 'ENTG', 'count': 62},
 {'ticker': 'APD', 'count': 61},
 {'ticker': 'AMT', 'count': 61},
 {'ticker': 'KHC', 'count': 61},
 {'ticker': 'BDX', 'count': 61},
 {'ticker': 'HBI', 'count': 60},
 {'ticker': 'ROK', 'count': 60},
 {'ticker': 'AMAT', 'count': 60},
 {'ticker': 'VEA', 'count': 59},
 {'ticker': 'MDLZ', 'count': 59},
 {'ticker': 'X', 'count': 59},
 {'ticker': 'MS', 'count': 59},
 {'ticker': 'SHLX', 'count': 58},
 {'ticker': 'WM', 'count': 58},
 {'ticker': 'ADI', 'count': 58},
 {'ticker': 'MMC', 'count': 58},
 {'ticker': 'GD', 'count': 57},
 {'ticker': 'ROP', 'count': 57},
 {'ticker': 'WY', 'count': 57},
 {'ticker': 'NWN', 'count': 57},
 {'ticker': 'REGN', 'count': 57},
 {'ticker': 'PNC', 'count': 57},
 {'ticker': 'FOXA', 'count': 57},
 {'ticker': 'BKNG', 'count': 57},
 {'ticker': 'BP', 'count': 57},
 {'ticker': 'LUV', 'count': 56},
 {'ticker': 'TRV', 'count': 56},
 {'ticker': 'NSC', 'count': 56},
 {'ticker': 'ICE', 'count': 56},
 {'ticker': 'MPC', 'count': 56},
 {'ticker': 'EMC', 'count': 56},
 {'ticker': 'DAL', 'count': 56},
 {'ticker': 'KLAC', 'count': 56},
 {'ticker': 'VLO', 'count': 56},
 {'ticker': 'CCI', 'count': 55},
 {'ticker': 'PRU', 'count': 55},
 {'ticker': 'QQQ', 'count': 55},
 {'ticker': 'PPL', 'count': 55},
 {'ticker': 'TMUS', 'count': 55},
 {'ticker': 'PGR', 'count': 55},
 {'ticker': 'IVZ', 'count': 55},
 {'ticker': 'VRSK', 'count': 55},
 {'ticker': 'USAC', 'count': 54},
 {'ticker': 'AZN', 'count': 54},
 {'ticker': 'HUYA', 'count': 53},
 {'ticker': 'EFX', 'count': 53},
 {'ticker': 'VOD', 'count': 53},
 {'ticker': 'EBAY', 'count': 53},
 {'ticker': 'MPLX', 'count': 53},
 {'ticker': 'RTX', 'count': 53},
 {'ticker': 'ENLC', 'count': 52},
 {'ticker': 'NWL', 'count': 52},
 {'ticker': 'TRGP', 'count': 52},
 {'ticker': 'CERN', 'count': 51},
 {'ticker': 'SH', 'count': 51},
 {'ticker': 'ETP', 'count': 51},
 {'ticker': 'IWD', 'count': 50},
 {'ticker': 'BK', 'count': 50},
 {'ticker': 'PXD', 'count': 50},
 {'ticker': 'SHW', 'count': 50},
 {'ticker': 'LRCX', 'count': 50},
 {'ticker': 'GEL', 'count': 50},
 {'ticker': 'SU', 'count': 50},
 {'ticker': 'BWXT', 'count': 49},
 {'ticker': 'LIN', 'count': 49},
 {'ticker': 'AZO', 'count': 49},
 {'ticker': 'CCK', 'count': 49},
 {'ticker': 'ITW', 'count': 49},
 {'ticker': 'IWF', 'count': 48},
 {'ticker': 'TWX', 'count': 48},
 {'ticker': 'IEMG', 'count': 48},
 {'ticker': 'ISRG', 'count': 47},
 {'ticker': 'RTN', 'count': 47},
 {'ticker': 'BIDU', 'count': 46},
 {'ticker': 'FCX', 'count': 46},
 {'ticker': 'WPZ', 'count': 46},
 {'ticker': 'GLD', 'count': 46},
 {'ticker': 'MMP', 'count': 46},
 {'ticker': 'SPGI', 'count': 46},
 {'ticker': 'DOV', 'count': 46},
 {'ticker': 'MU', 'count': 46},
 {'ticker': 'RF', 'count': 45},
 {'ticker': 'PRGO', 'count': 45},
 {'ticker': 'SYF', 'count': 45},
 {'ticker': 'FISV', 'count': 44},
 {'ticker': 'PX', 'count': 44},
 {'ticker': 'LKQ', 'count': 44},
 {'ticker': 'STX', 'count': 44},
 {'ticker': 'SWK', 'count': 44},
 {'ticker': 'VLP', 'count': 43},
 {'ticker': 'AAN', 'count': 43},
 {'ticker': 'ALL', 'count': 43},
 {'ticker': 'BUD', 'count': 43},
 {'ticker': 'NXPI', 'count': 43},
 {'ticker': 'CTL', 'count': 43},
 {'ticker': 'TEL', 'count': 43},
 {'ticker': 'TAP', 'count': 43},
 {'ticker': 'DIA', 'count': 42},
 {'ticker': 'PSQ', 'count': 42},
 {'ticker': 'CMI', 'count': 42},
 {'ticker': 'HYH', 'count': 42},
 {'ticker': 'PCLN', 'count': 42},
 {'ticker': 'TSN', 'count': 42},
 {'ticker': 'RHT', 'count': 41},
 {'ticker': 'UBER', 'count': 41},
 {'ticker': 'FSLR', 'count': 41},
 {'ticker': 'FITB', 'count': 41},
 {'ticker': 'INFO', 'count': 41},
 {'ticker': 'CRWD', 'count': 41},
 {'ticker': 'CCL', 'count': 41},
 {'ticker': 'ADSK', 'count': 40},
 {'ticker': 'SNY', 'count': 40},
 {'ticker': 'PSXP', 'count': 40},
 {'ticker': 'DLTR', 'count': 40},
 {'ticker': 'DGX', 'count': 40},
 {'ticker': 'LYB', 'count': 39},
 {'ticker': 'OMC', 'count': 39},
 {'ticker': 'STZ', 'count': 39},
 {'ticker': 'CNC', 'count': 39},
 {'ticker': 'AIG', 'count': 39},
 {'ticker': 'ETE', 'count': 39},
 {'ticker': 'PANW', 'count': 39},
 {'ticker': 'AFL', 'count': 38},
 {'ticker': 'TOT', 'count': 38},
 {'ticker': 'SNAP', 'count': 38},
 {'ticker': 'MRO', 'count': 38},
 {'ticker': 'BLL', 'count': 38},
 {'ticker': 'BBT', 'count': 38},
 {'ticker': 'BEN', 'count': 38},
 {'ticker': 'LGF-B', 'count': 37},
 {'ticker': 'JWN', 'count': 37},
 {'ticker': 'DWDP', 'count': 37},
 {'ticker': 'IFNNY', 'count': 37},
 {'ticker': 'ASML', 'count': 36},
 {'ticker': 'AA', 'count': 36},
 {'ticker': 'ALB', 'count': 36},
 {'ticker': 'MNST', 'count': 36},
 {'ticker': 'VSLR', 'count': 36},
 {'ticker': 'BBVA', 'count': 36},
 {'ticker': 'VB', 'count': 36},
 {'ticker': 'ARCC', 'count': 36},
 {'ticker': 'ALGN', 'count': 35},
 {'ticker': 'MAR', 'count': 35},
 {'ticker': 'TYC', 'count': 35},
 {'ticker': 'KSU', 'count': 35},
 {'ticker': 'MSCI', 'count': 35},
 {'ticker': 'PBFX', 'count': 35},
 {'ticker': 'EOG', 'count': 35},
 {'ticker': 'HPQ', 'count': 35},
 {'ticker': 'VIG', 'count': 35},
 {'ticker': 'WFM', 'count': 35},
 {'ticker': 'CR', 'count': 35},
 {'ticker': 'LH', 'count': 35},
 {'ticker': 'FAST', 'count': 34},
 {'ticker': 'GPN', 'count': 34},
 {'ticker': 'CHTR', 'count': 34},
 {'ticker': 'BKI', 'count': 34},
 {'ticker': 'REVB', 'count': 34},
 {'ticker': 'NOW', 'count': 34},
 {'ticker': 'ADT', 'count': 34},
 {'ticker': 'TRP', 'count': 34},
 {'ticker': 'AEP', 'count': 33},
 {'ticker': 'VSM', 'count': 33},
 {'ticker': 'COH', 'count': 33},
 {'ticker': 'HCA', 'count': 33},
 {'ticker': 'ENBL', 'count': 33},
 {'ticker': 'ILMN', 'count': 33},
 {'ticker': 'NGLS', 'count': 33},
 {'ticker': 'LEA', 'count': 33},
 {'ticker': 'CHL', 'count': 33},
 {'ticker': 'SCI', 'count': 32},
 {'ticker': 'WYNN', 'count': 32},
 {'ticker': 'CMG', 'count': 32},
 {'ticker': 'CIT', 'count': 32},
 {'ticker': 'SJM', 'count': 32},
 {'ticker': 'ABC', 'count': 32},
 {'ticker': 'SRCL', 'count': 32},
 {'ticker': 'AMP', 'count': 32},
 {'ticker': 'SPLK', 'count': 32},
 {'ticker': 'ENB', 'count': 32},
 {'ticker': 'AON', 'count': 32},
 {'ticker': 'APC', 'count': 31},
 {'ticker': 'TCEHY', 'count': 31},
 {'ticker': 'LNT', 'count': 31},
 {'ticker': 'WRK', 'count': 31},
 {'ticker': 'ROKU', 'count': 31},
 {'ticker': 'PLD', 'count': 31},
 {'ticker': 'IWM', 'count': 31},
 {'ticker': 'WLK', 'count': 31},
 {'ticker': 'SRE', 'count': 31},
 {'ticker': 'APA', 'count': 31},
 {'ticker': 'ANTM', 'count': 31},
 {'ticker': 'AKAM', 'count': 30},
 {'ticker': 'SAP', 'count': 30},
 {'ticker': 'LHX', 'count': 30},
 {'ticker': 'TT', 'count': 30},
 {'ticker': 'EQIX', 'count': 30},
 {'ticker': 'NLY', 'count': 30},
 {'ticker': 'LVS', 'count': 30},
 {'ticker': 'ECOM', 'count': 30},
 {'ticker': 'CSX', 'count': 30},
 {'ticker': 'RAND', 'count': 30},
 {'ticker': 'RIO', 'count': 30},
 {'ticker': 'VTR', 'count': 30},
 {'ticker': 'BHP', 'count': 30},
 {'ticker': 'MCHP', 'count': 30},
 {'ticker': 'EXPE', 'count': 30},
 {'ticker': 'NDAQ', 'count': 30},
 {'ticker': 'DPSGY', 'count': 30},
 {'ticker': 'PH', 'count': 30},
 {'ticker': 'ADM', 'count': 30},
 {'ticker': 'KTOS', 'count': 30},
 {'ticker': 'AXTA', 'count': 29},
 {'ticker': 'AJG', 'count': 29},
 {'ticker': 'PLNT', 'count': 29},
 {'ticker': 'SSNC', 'count': 29},
 {'ticker': 'HSBC', 'count': 29},
 {'ticker': 'SSEZY', 'count': 29},
 {'ticker': 'CHKP', 'count': 29},
 {'ticker': 'CHD', 'count': 29},
 {'ticker': 'MTB', 'count': 29},
 {'ticker': 'BTI', 'count': 29},
 {'ticker': 'FANUY', 'count': 29},
 {'ticker': 'EXAS', 'count': 29},
 {'ticker': 'CGNX', 'count': 29},
 {'ticker': 'NOV', 'count': 29},
 {'ticker': 'NTAP', 'count': 28},
 {'ticker': 'STI', 'count': 28},
 {'ticker': 'W', 'count': 28},
 {'ticker': 'CSGP', 'count': 28},
 {'ticker': 'LNG', 'count': 28},
 {'ticker': 'ACE', 'count': 28},
 {'ticker': 'MAT', 'count': 28},
 {'ticker': 'CE', 'count': 28},
 {'ticker': 'BAYRY', 'count': 28},
 {'ticker': 'CAH', 'count': 28},
 {'ticker': 'ALXN', 'count': 28},
 {'ticker': 'SVNLY', 'count': 28},
 {'ticker': 'FLR', 'count': 28},
 {'ticker': 'ORLY', 'count': 28},
 {'ticker': 'NGG', 'count': 28},
 {'ticker': 'TEVA', 'count': 28},
 {'ticker': 'TFC', 'count': 28},
 {'ticker': 'SSB', 'count': 28},
 {'ticker': 'ZBRA', 'count': 28},
 {'ticker': 'K', 'count': 28},
 {'ticker': 'Z', 'count': 28},
 {'ticker': 'COIN', 'count': 28},
 {'ticker': 'AOS', 'count': 28},
 {'ticker': 'IRM', 'count': 28},
 {'ticker': 'IR', 'count': 28},
 {'ticker': 'NBLX', 'count': 27},
 {'ticker': 'SIX', 'count': 27},
 {'ticker': 'RDS.A', 'count': 27},
 {'ticker': 'RAI', 'count': 27},
 {'ticker': 'DLPH', 'count': 27},
 {'ticker': 'PFS', 'count': 27},
 {'ticker': 'YUM', 'count': 27},
 {'ticker': 'BCE', 'count': 27},
 {'ticker': 'UBS', 'count': 27},
 {'ticker': 'PCAR', 'count': 27},
 {'ticker': 'OLED', 'count': 27},
 {'ticker': 'PAYX', 'count': 27},
 {'ticker': 'CFG', 'count': 27},
 {'ticker': 'WCC', 'count': 27},
 {'ticker': 'HAL', 'count': 27},
 {'ticker': 'GBIL', 'count': 27},
 {'ticker': 'CXW', 'count': 26},
 {'ticker': 'TDOC', 'count': 26},
 {'ticker': 'VOE', 'count': 26},
 {'ticker': 'BOIVF', 'count': 26},
 {'ticker': 'AZSEY', 'count': 26},
 {'ticker': 'IFF', 'count': 26},
 {'ticker': 'ARLP', 'count': 26},
 {'ticker': 'HSY', 'count': 26},
 {'ticker': 'LW', 'count': 26},
 {'ticker': 'TDG', 'count': 26},
 {'ticker': 'LSXMK', 'count': 26},
 {'ticker': 'IQV', 'count': 26},
 {'ticker': 'HIG', 'count': 26},
 {'ticker': 'ULTA', 'count': 26},
 {'ticker': 'KEY', 'count': 26},
 {'ticker': 'EWBC', 'count': 26},
 {'ticker': 'PTON', 'count': 26},
 {'ticker': 'FDN', 'count': 26},
 {'ticker': 'ADS', 'count': 26},
 {'ticker': 'A', 'count': 26},
 {'ticker': 'AMTD', 'count': 26},
 {'ticker': 'EW', 'count': 26},
 {'ticker': 'XEL', 'count': 25},
 {'ticker': 'ROST', 'count': 25},
 {'ticker': 'MWE', 'count': 25},
 {'ticker': 'FE', 'count': 25},
 {'ticker': 'EXPD', 'count': 25},
 {'ticker': 'TMK', 'count': 25},
 {'ticker': 'HDS', 'count': 25},
 {'ticker': 'BAESY', 'count': 25},
 {'ticker': 'CAG', 'count': 25},
 {'ticker': 'POT', 'count': 25},
 {'ticker': 'SDY', 'count': 25},
 {'ticker': 'TSCO', 'count': 25},
 {'ticker': 'FLS', 'count': 25},
 {'ticker': 'LULU', 'count': 25},
 {'ticker': 'PHG', 'count': 25},
 {'ticker': 'UA', 'count': 25},
 {'ticker': 'SNE', 'count': 25},
 {'ticker': 'WES', 'count': 25},
 {'ticker': 'COV', 'count': 25},
 {'ticker': 'SPCE', 'count': 25},
 {'ticker': 'IT', 'count': 25},
 {'ticker': 'FOX', 'count': 25},
 {'ticker': 'DOX', 'count': 25},
 {'ticker': 'DASTY', 'count': 25},
 {'ticker': 'ABNB', 'count': 25},
 {'ticker': 'OCR', 'count': 25},
 {'ticker': 'RDS.B', 'count': 25},
 {'ticker': 'IWN', 'count': 25},
 {'ticker': 'VAR', 'count': 25},
 {'ticker': 'MCO', 'count': 24},
 {'ticker': 'AEE', 'count': 24},
 {'ticker': 'USG', 'count': 24},
 {'ticker': 'CMCSK', 'count': 24},
 {'ticker': 'FLIR', 'count': 24},
 {'ticker': 'CTLT', 'count': 24},
 {'ticker': 'HUN', 'count': 24},
 {'ticker': 'PKI', 'count': 24},
 {'ticker': 'EFA', 'count': 24},
 {'ticker': 'MTCH', 'count': 24},
 {'ticker': 'BXS', 'count': 24},
 {'ticker': 'DASH', 'count': 24},
 {'ticker': 'IACI', 'count': 24},
 {'ticker': 'BPL', 'count': 24},
 {'ticker': 'VIAC', 'count': 24},
 {'ticker': 'QEP', 'count': 24},
 {'ticker': 'DPZ', 'count': 24},
 {'ticker': 'DORM', 'count': 24},
 {'ticker': 'RPM', 'count': 24},
 {'ticker': 'GWW', 'count': 24},
 {'ticker': 'PSO', 'count': 24},
 {'ticker': 'PFF', 'count': 24},
 {'ticker': 'EQR', 'count': 24},
 {'ticker': 'BAH', 'count': 24},
 {'ticker': 'KMX', 'count': 24},
 {'ticker': 'DKNG', 'count': 24},
 {'ticker': 'ES', 'count': 24},
 {'ticker': 'TD', 'count': 23},
 {'ticker': 'RSG', 'count': 23},
 {'ticker': 'MYL', 'count': 23},
 {'ticker': 'OLP', 'count': 23},
 {'ticker': 'AXS', 'count': 23},
 {'ticker': 'L', 'count': 23},
 {'ticker': 'VRTX', 'count': 23},
 {'ticker': 'MAS', 'count': 23},
 {'ticker': 'WBD', 'count': 23},
 {'ticker': 'BWA', 'count': 23},
 {'ticker': 'FTV', 'count': 23},
 {'ticker': 'MAC', 'count': 23},
 {'ticker': 'LO', 'count': 23},
 {'ticker': 'URI', 'count': 23},
 {'ticker': 'ELAN', 'count': 22},
 {'ticker': 'SITE', 'count': 22},
 {'ticker': 'CG', 'count': 22},
 {'ticker': 'HBAN', 'count': 22},
 {'ticker': 'SEE', 'count': 22},
 {'ticker': 'BTID', 'count': 22},
 {'ticker': 'CF', 'count': 22},
 {'ticker': 'XLF', 'count': 22},
 {'ticker': 'ZBH', 'count': 22},
 {'ticker': 'USDP', 'count': 22},
 {'ticker': 'EQT', 'count': 22},
 {'ticker': 'UBSI', 'count': 22},
 {'ticker': 'GDDY', 'count': 22},
 {'ticker': 'WEC', 'count': 22},
 {'ticker': 'SIEGY', 'count': 21},
 {'ticker': 'CMA', 'count': 21},
 {'ticker': 'DLR', 'count': 21},
 {'ticker': 'DXCM', 'count': 21},
 {'ticker': 'SSYS', 'count': 21},
 {'ticker': 'BMRN', 'count': 21},
 {'ticker': 'VOT', 'count': 21},
 {'ticker': 'SGBK', 'count': 21},
 {'ticker': 'HAS', 'count': 21},
 {'ticker': 'NEM', 'count': 21},
 {'ticker': 'WTW', 'count': 21},
 {'ticker': 'HSIC', 'count': 21},
 {'ticker': 'TROW', 'count': 21},
 {'ticker': 'CTVA', 'count': 21},
 {'ticker': 'BKCC', 'count': 21},
 {'ticker': 'HHC', 'count': 21},
 {'ticker': 'APTV', 'count': 21},
 {'ticker': 'EXC', 'count': 20},
 {'ticker': 'FCEL', 'count': 20},
 {'ticker': 'FLEX', 'count': 20},
 {'ticker': 'APOL', 'count': 20},
 {'ticker': 'AES', 'count': 20},
 {'ticker': 'PBA', 'count': 20},
 {'ticker': 'GOLD', 'count': 20},
 {'ticker': 'FTNT', 'count': 20},
 {'ticker': 'CWEN.A', 'count': 20},
 {'ticker': 'CLB', 'count': 20},
 {'ticker': 'SUN', 'count': 20},
 {'ticker': 'REZI', 'count': 20},
 {'ticker': 'TFX', 'count': 20},
 {'ticker': 'WAB', 'count': 20},
 {'ticker': 'BASFY', 'count': 20},
 {'ticker': 'RSP', 'count': 20},
 {'ticker': 'HLT', 'count': 20},
 {'ticker': 'ONNN', 'count': 20},
 {'ticker': 'VIVHY', 'count': 20},
 {'ticker': 'PII', 'count': 20},
 {'ticker': 'BYND', 'count': 20},
 {'ticker': 'RBLX', 'count': 20},
 {'ticker': 'LVMUY', 'count': 20},
 {'ticker': 'BXP', 'count': 20},
 {'ticker': 'NTRS', 'count': 20},
 {'ticker': 'NWSA', 'count': 20},
 {'ticker': 'CYRX', 'count': 20},
 {'ticker': 'LDOS', 'count': 20},
 {'ticker': 'HTZ', 'count': 20},
 {'ticker': 'CARR', 'count': 20},
 {'ticker': 'BRCD', 'count': 20},
 {'ticker': 'ADDYY', 'count': 20},
 {'ticker': 'XLNX', 'count': 19},
 {'ticker': 'VGR', 'count': 19},
 {'ticker': 'ERIC', 'count': 19},
 {'ticker': 'MRNA', 'count': 19},
 {'ticker': 'AYI', 'count': 19},

In [5]:
"""
For each transaction get price of ticker at that date
"""
TICKER_LIST_FOLDER_PATH = join(get_out_folder_analysis(), "ticker_prices")
available_ticker_price = set([tkr.removesuffix(".csv").upper() for tkr in listdir(TICKER_LIST_FOLDER_PATH)])

ticker_df = master_df.dropna(subset="ticker")
ticker_df = ticker_df[ticker_df["ticker"].isin(available_ticker_price)]
ticker_df = ticker_df.sort_values(by="ticker").reset_index(drop=True)

price_df: pd.DataFrame = None
last_ticker = None
ticker_list = ticker_df.to_dict(orient="records")
for row in ticker_list:
    ticker:str = row["ticker"]
    if last_ticker != ticker:
        last_ticker = ticker
        price_file_path = join(TICKER_LIST_FOLDER_PATH, ticker.lower() + ".csv")
        price_df = pd.read_csv(price_file_path)
        price_df["Date"] = pd.to_datetime( price_df["Date"], format="%m/%d/%Y")
    
    transaction_date: pd.Timestamp = pd.to_datetime(row["transaction_date"])
    price_row = price_df[price_df["Date"] == transaction_date]
    if price_row.size != 6:
        continue
    price_row = price_row.iloc[0]

    _, close_price, trade_volume, open_price, high_price, low_price = price_row.to_list() 

    def format_price(in_price):
        if not isinstance(in_price, str):
            return np.nan
        
        in_price = in_price.replace("$", "")
        return float(in_price)

    row["open_price"] = format_price(open_price)
    row["close_price"] = format_price(close_price)
    row["low_price"] = format_price(low_price)
    row["high_price"] = format_price(high_price)
    row["trade_volume"] = format_price(trade_volume)

ticker_df = pd.DataFrame(ticker_list)
    
ticker_df

,transaction_date,politician_first_name,politician_last_name,office,district,asset_name,asset_type,ticker,owner,action_type,...,doc_id,lower_bound_amount,upper_bound_amount,average_amount,politician_name,open_price,close_price,low_price,high_price,trade_volume
0,2018-04-13,LAMAR,SMITH,H,TX21,"AGILENT TECHNOLOGIES, INC.",ST,A,SELF,P,...,20009430,1001.0,15000.0,8000.5,LAMAR SMITH,67.500,67.21,66.880,67.6700,NaN
1,2018-05-16,LAMAR,SMITH,H,TX21,"AGILENT TECHNOLOGIES, INC.",ST,A,SELF,P,...,20009707,1001.0,15000.0,8000.5,LAMAR SMITH,62.510,61.94,61.650,62.9883,NaN
2,2014-02-14,ROBERT-P,CORKER-JR,S,NaN,Agilent Technologies Inc. (NYSE),NaN,A,SELF,S,...,9eeb2456-9f74-4f17-8cc8-d9baa6a24023,1001.0,15000.0,8000.5,ROBERT-P CORKER-JR,NaN,NaN,NaN,NaN,NaN
3,2023-10-16,THOMAS-H,TUBERVILLE,S,NaN,Agilent Technologies,ST,A,JT,S,...,25e0814a-7ea9-41b7-96e6-9c59fbc8c0e3,1001.0,15000.0,8000.5,THOMAS-H TUBERVILLE,111.040,111.50,109.640,112.7900,NaN
4,2014-02-14,ROBERT-P,CORKER-JR,S,NaN,Agilent Technologies Inc. (NYSE),NaN,A,SELF,S,...,e3472690-e844-4636-9cec-cfc3ccf7ab35,1001.0,15000.0,8000.5,ROBERT-P CORKER-JR,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44495,2019-03-25,NICHOLAS-VAN,TAYLOR,H,TX03,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SP,S,...,20011315,1001.0,15000.0,8000.5,NICHOLAS-VAN TAYLOR,33.080,32.97,32.940,33.1040,NaN
44496,2023-07-10,DANIEL,GOLDMAN,H,NY10,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,20023404,1001.0,15000.0,8000.5,DANIEL GOLDMAN,46.215,46.26,46.130,46.4350,NaN
44497,2023-01-13,DANIEL,GOLDMAN,H,NY10,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,20022407,15001.0,50000.0,32500.5,DANIEL GOLDMAN,47.860,48.11,47.630,48.1400,NaN
44498,2017-07-11,JOHN,RUTHERFORD,H,FL04,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,P,...,20009815,1001.0,15000.0,8000.5,JOHN RUTHERFORD,29.650,29.79,29.530,29.7900,NaN
44499,2022-03-16,JOHN,RUTHERFORD,H,FL04,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,20020828,1001.0,15000.0,8000.5,JOHN RUTHERFORD,46.750,46.61,45.782,46.9700,NaN

In [6]:
# Process further
ticker_df = ticker_df.dropna(subset="open_price")
def get_average_ticker_price(in_row):
    open_price, close_price = in_row["open_price"], in_row["close_price"]
    return (open_price + close_price) / 2
    
ticker_df["average_price"] = ticker_df.apply(get_average_ticker_price, axis=1)
ticker_df = ticker_df[ticker_df["average_price"] > 0]

def get_units_transacted(in_row):
    average_amount, average_price = in_row["average_amount"], in_row["average_price"]
    return math.ceil(average_amount / average_price)

ticker_df["units_transacted"] = ticker_df.apply(get_units_transacted, axis=1)

ticker_df

C:\Users\fdirham\AppData\Local\Temp\ipykernel_48908\3180572723.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ticker_df["average_price"] = ticker_df.apply(get_average_ticker_price, axis=1)

,transaction_date,politician_first_name,politician_last_name,office,district,asset_name,asset_type,ticker,owner,action_type,...,upper_bound_amount,average_amount,politician_name,open_price,close_price,low_price,high_price,trade_volume,average_price,units_transacted
0,2018-04-13,LAMAR,SMITH,H,TX21,"AGILENT TECHNOLOGIES, INC.",ST,A,SELF,P,...,15000.0,8000.5,LAMAR SMITH,67.500,67.21,66.880,67.6700,NaN,67.3550,119
1,2018-05-16,LAMAR,SMITH,H,TX21,"AGILENT TECHNOLOGIES, INC.",ST,A,SELF,P,...,15000.0,8000.5,LAMAR SMITH,62.510,61.94,61.650,62.9883,NaN,62.2250,129
3,2023-10-16,THOMAS-H,TUBERVILLE,S,NaN,Agilent Technologies,ST,A,JT,S,...,15000.0,8000.5,THOMAS-H TUBERVILLE,111.040,111.50,109.640,112.7900,NaN,111.2700,72
5,2019-06-24,DONNA,SHALALA,H,FL27,HYATT HOTELS CORPORATION CLASS A ML,ST,A,SELF,S,...,15000.0,8000.5,DONNA SHALALA,73.330,73.14,72.260,73.6800,NaN,73.2350,110
7,2019-04-03,DONNA,SHALALA,H,FL27,HYATT HOTELS CORPORATION CLASS A,ST,A,SELF,P,...,15000.0,8000.5,DONNA SHALALA,81.540,81.94,81.460,82.0200,NaN,81.7400,98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44495,2019-03-25,NICHOLAS-VAN,TAYLOR,H,TX03,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SP,S,...,15000.0,8000.5,NICHOLAS-VAN TAYLOR,33.080,32.97,32.940,33.1040,NaN,33.0250,243
44496,2023-07-10,DANIEL,GOLDMAN,H,NY10,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,15000.0,8000.5,DANIEL GOLDMAN,46.215,46.26,46.130,46.4350,NaN,46.2375,174
44497,2023-01-13,DANIEL,GOLDMAN,H,NY10,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,50000.0,32500.5,DANIEL GOLDMAN,47.860,48.11,47.630,48.1400,NaN,47.9850,678
44498,2017-07-11,JOHN,RUTHERFORD,H,FL04,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,P,...,15000.0,8000.5,JOHN RUTHERFORD,29.650,29.79,29.530,29.7900,NaN,29.7200,270
44499,2022-03-16,JOHN,RUTHERFORD,H,FL04,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,15000.0,8000.5,JOHN RUTHERFORD,46.750,46.61,45.782,46.9700,NaN,46.6800,172

In [7]:
# Save ticker df
ticker_df_save_path = join(get_out_folder_analysis(), "transaction_with_prices_df.csv")
ticker_df.to_csv(ticker_df_save_path, encoding="utf-8", index=False)
ticker_df

,transaction_date,politician_first_name,politician_last_name,office,district,asset_name,asset_type,ticker,owner,action_type,...,upper_bound_amount,average_amount,politician_name,open_price,close_price,low_price,high_price,trade_volume,average_price,units_transacted
0,2018-04-13,LAMAR,SMITH,H,TX21,"AGILENT TECHNOLOGIES, INC.",ST,A,SELF,P,...,15000.0,8000.5,LAMAR SMITH,67.500,67.21,66.880,67.6700,NaN,67.3550,119
1,2018-05-16,LAMAR,SMITH,H,TX21,"AGILENT TECHNOLOGIES, INC.",ST,A,SELF,P,...,15000.0,8000.5,LAMAR SMITH,62.510,61.94,61.650,62.9883,NaN,62.2250,129
3,2023-10-16,THOMAS-H,TUBERVILLE,S,NaN,Agilent Technologies,ST,A,JT,S,...,15000.0,8000.5,THOMAS-H TUBERVILLE,111.040,111.50,109.640,112.7900,NaN,111.2700,72
5,2019-06-24,DONNA,SHALALA,H,FL27,HYATT HOTELS CORPORATION CLASS A ML,ST,A,SELF,S,...,15000.0,8000.5,DONNA SHALALA,73.330,73.14,72.260,73.6800,NaN,73.2350,110
7,2019-04-03,DONNA,SHALALA,H,FL27,HYATT HOTELS CORPORATION CLASS A,ST,A,SELF,P,...,15000.0,8000.5,DONNA SHALALA,81.540,81.94,81.460,82.0200,NaN,81.7400,98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44495,2019-03-25,NICHOLAS-VAN,TAYLOR,H,TX03,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SP,S,...,15000.0,8000.5,NICHOLAS-VAN TAYLOR,33.080,32.97,32.940,33.1040,NaN,33.0250,243
44496,2023-07-10,DANIEL,GOLDMAN,H,NY10,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,15000.0,8000.5,DANIEL GOLDMAN,46.215,46.26,46.130,46.4350,NaN,46.2375,174
44497,2023-01-13,DANIEL,GOLDMAN,H,NY10,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,50000.0,32500.5,DANIEL GOLDMAN,47.860,48.11,47.630,48.1400,NaN,47.9850,678
44498,2017-07-11,JOHN,RUTHERFORD,H,FL04,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,P,...,15000.0,8000.5,JOHN RUTHERFORD,29.650,29.79,29.530,29.7900,NaN,29.7200,270
44499,2022-03-16,JOHN,RUTHERFORD,H,FL04,ZURICH INSURANCE GROUP LIMITED SPONSORED AMERI...,ST,ZURVY,SELF,S,...,15000.0,8000.5,JOHN RUTHERFORD,46.750,46.61,45.782,46.9700,NaN,46.6800,172

In [8]:
"""ANALYSIS STARTS HERE"""
pass

In [9]:
# How many did each person spend trading stocks?
personal_spending_df = master_df.groupby('politician_name').agg({
    "lower_bound_amount": "sum",
    "upper_bound_amount": "sum",
    "average_amount": "sum",
}).reset_index()
personal_spending_df.sort_values(by="average_amount", ascending=False)

,politician_name,lower_bound_amount,upper_bound_amount,average_amount
360,SUZAN-K DELBENE,1.365226e+08,4.574300e+08,2.969763e+08
161,JOSH GOTTHEIMER,8.439557e+07,3.782460e+08,2.313208e+08
340,SCOTT-H PETERS,1.749167e+08,2.813900e+08,2.281533e+08
315,RICK SCOTT,1.017052e+08,2.842750e+08,1.929901e+08
286,NANCY PELOSI,6.214118e+07,2.009400e+08,1.315406e+08
...,...,...,...,...
243,MR-JAMES-R LANGEVIN,1.001000e+03,1.500000e+04,8.000500e+03
322,ROBERT-P CASEY-JR,1.001000e+03,1.500000e+04,8.000500e+03
248,MR-KEVIN YODER,1.001000e+03,1.500000e+04,8.000500e+03
316,ROB WOODALL,1.001000e+03,1.500000e+04,8.000500e+03
193,MARCY KAPTUR,1.280030e+03,1.280030e+03,1.280030e+03

In [10]:
# How many did each person spend trading stocks that we know of
personal_spending_df = ticker_df.groupby('politician_name').agg({
    "lower_bound_amount": "sum",
    "upper_bound_amount": "sum",
    "average_amount": "sum",
}).reset_index()
personal_spending_df.sort_values(by="average_amount", ascending=False)

       politician_name  lower_bound_amount  upper_bound_amount  average_amount
125    JOSH GOTTHEIMER         83756208.00        3.721860e+08    2.279711e+08
268    SUZAN-K DELBENE         59669107.00        2.797100e+08    1.696896e+08
132     KELLY LOEFFLER         46480326.00        1.899750e+08    1.182277e+08
211       NANCY PELOSI         51583137.00        1.734450e+08    1.125141e+08
83      GREG GIANFORTE         41912007.00        1.042050e+08    7.305851e+07
..                 ...                 ...                 ...             ...
259     STEPHANIE BICE             1001.00        1.500000e+04    8.000500e+03
239  ROBERT-P CASEY-JR             1001.00        1.500000e+04    8.000500e+03
242     ROGER WILLIAMS             1001.00        1.500000e+04    8.000500e+03
184   MR-JIM MCDERMOTT             1001.00        1.500000e+04    8.000500e+03
149       MARCY KAPTUR             1280.03        1.280030e+03    1.280030e+03

[297 rows x 4 columns]